package com;

public class Computer {
	MotherBoard mb;
	KeyBoard kb;
	Cpu cpu;
	Mouse mouse;
	Ram ram;
	Monitor monitor;

	public void display()
	{
		System.out.println();
		System.out.println();
		System.out.println("MotherBoard Configuration:");
		System.out.println("\t Company Name		: "+mb.c.name);
		System.out.println("\t MotherBoard Id		: "+mb.id);
		System.out.println("\t Quality Rating		: "+mb.qualityRating);
		System.out.println("\t Warrenty 		: "+mb.warrentyPeriod);
		System.out.println("\t Company Id		: "+mb.c.id);
		System.out.println("\t Company Email		: "+mb.c.email);
		System.out.println("\t Company Address	: d.no:-"+mb.c.c.d_no+",");
		System.out.println("\t\t\t\t  "+mb.c.c.street+",");
		System.out.println("\t\t\t\t  "+mb.c.c.state+",");
		System.out.println("\t\t\t\t  "+mb.c.c.city+",");
		System.out.println("\t\t\t\t  "+mb.c.c.country+",");
		System.out.println("\t\t\t\t  "+mb.c.c.pin+",");
		System.out.println();
		System.out.println("KeyBoard Configuration:");
		System.out.println("\t Company Name		: "+kb.c.name);
		System.out.println("\t KeyBoard Id		: "+kb.id);
		System.out.println("\t Quality Rating		: "+kb.qualityRating);
		System.out.println("\t Warrenty 		: "+kb.warrentyPeriod);
		System.out.println("\t Company Id		: "+kb.c.id);
		System.out.println("\t Company Email		: "+kb.c.email);
		System.out.println("\t Company Address	: d.no:-"+kb.c.c.d_no+",");
		System.out.println("\t\t\t\t  "+kb.c.c.street+",");
		System.out.println("\t\t\t\t  "+kb.c.c.state+",");
		System.out.println("\t\t\t\t  "+kb.c.c.city+",");
		System.out.println("\t\t\t\t  "+kb.c.c.country+",");
		System.out.println("\t\t\t\t  "+kb.c.c.pin);
		System.out.println();
		System.out.println("CPU Configuration:");
		System.out.println("\t Company Name		: "+cpu.c.name);
		System.out.println("\t CPU Id			: "+cpu.id);
		System.out.println("\t CPU Speed		: "+cpu.speed);
		System.out.println("\t CPU type		: "+cpu.type);
		System.out.println("\t Quality Rating		: "+cpu.qualityRating);
		System.out.println("\t Warrenty 		: "+cpu.warrentyPeriod);
		System.out.println("\t Company Id		: "+cpu.c.id);
		System.out.println("\t Company Email		: "+cpu.c.email);
		System.out.println("\t Company Address	: d.no:-"+cpu.c.c.d_no+",");
		System.out.println("\t\t\t\t  "+cpu.c.c.street+",");
		System.out.println("\t\t\t\t  "+cpu.c.c.state+",");
		System.out.println("\t\t\t\t  "+cpu.c.c.city+",");
		System.out.println("\t\t\t\t  "+cpu.c.c.country+",");
		System.out.println("\t\t\t\t  "+cpu.c.c.pin);
		System.out.println();
		System.out.println("Mouse Configuration:");
		System.out.println("\t Company Name		: "+mouse.c.name);
		System.out.println("\t Mouse Id		: "+mouse.id);
		System.out.println("\t Mouse type		: "+mouse.type);
		System.out.println("\t Quality Rating		: "+mouse.qualityRating);
		System.out.println("\t Warrenty 		: "+mouse.warrentyPeriod);
		System.out.println("\t Company Id		: "+mouse.c.id);
		System.out.println("\t Company Email		: "+mouse.c.email);
		System.out.println("\t Company Address	: d.no:-"+mouse.c.c.d_no+",");
		System.out.println("\t\t\t\t  "+mouse.c.c.street+",");
		System.out.println("\t\t\t\t  "+mouse.c.c.state+",");
		System.out.println("\t\t\t\t  "+mouse.c.c.city+",");
		System.out.println("\t\t\t\t  "+mouse.c.c.country+",");
		System.out.println("\t\t\t\t  "+mouse.c.c.pin);
		System.out.println();
		System.out.println("RAM Configuration:");
		System.out.println("\t Company Name		: "+ram.c.name);
		System.out.println("\t Ram Id			: "+ram.id);
		System.out.println("\t Ram capacity		: "+ram.capacity);
		System.out.println("\t Quality Rating		: "+ram.qualityRating);
		System.out.println("\t Warrenty 		: "+ram.warrentyPeriod);
		System.out.println("\t Company Id		: "+ram.c.id);
		System.out.println("\t Company Email		: "+ram.c.email);
		System.out.println("\t Company Address	: d.no:-"+ram.c.c.d_no+",");
		System.out.println("\t\t\t\t  "+ram.c.c.street+",");
		System.out.println("\t\t\t\t  "+ram.c.c.state+",");
		System.out.println("\t\t\t\t  "+ram.c.c.city+",");
		System.out.println("\t\t\t\t  "+ram.c.c.country+",");
		System.out.println("\t\t\t\t  "+ram.c.c.pin);
		System.out.println();
		System.out.println("Monitor Configuration:");
		System.out.println("\t Company Name		: "+monitor.c.name);
		System.out.println("\t monitor Id		: "+monitor.id);
		System.out.println("\t monitor width		: "+monitor.width);
		System.out.println("\t monitor height		: "+monitor.height);
		System.out.println("\t Quality Rating		: "+monitor.qualityRating);
		System.out.println("\t Warrenty 		: "+monitor.warrentyPeriod);
		System.out.println("\t Company Id		: "+monitor.c.id);
		System.out.println("\t Company Email		: "+monitor.c.email);
		System.out.println("\t Company Address	: d.no:-"+monitor.c.c.d_no+",");
		System.out.println("\t\t\t\t  "+monitor.c.c.street+",");
		System.out.println("\t\t\t\t  "+monitor.c.c.state+",");
		System.out.println("\t\t\t\t  "+monitor.c.c.city+",");
		System.out.println("\t\t\t\t  "+monitor.c.c.country+",");
		System.out.println("\t\t\t\t  "+monitor.c.c.pin);
		System.out.println();
		
		int bpp=mb.B.baseProductPrice+kb.B.baseProductPrice+cpu.B.baseProductPrice+mouse.B.baseProductPrice+ram.B.baseProductPrice+monitor.B.baseProductPrice;
		int st=mb.B.serviceTax+kb.B.serviceTax+cpu.B.serviceTax+mouse.B.serviceTax+ram.B.serviceTax+monitor.B.serviceTax;
		int tt=mb.B.TransportTax+kb.B.TransportTax+cpu.B.TransportTax+mouse.B.TransportTax+ram.B.TransportTax+monitor.B.TransportTax;
		double stt=mb.B.stateTax+kb.B.stateTax+cpu.B.stateTax+mouse.B.stateTax+ram.B.stateTax+monitor.B.stateTax;
		double ct=mb.B.centralTax+kb.B.centralTax+cpu.B.centralTax+mouse.B.centralTax+ram.B.centralTax+monitor.B.centralTax;
		double fp=mb.B.finalPrice+kb.B.finalPrice+cpu.B.finalPrice+mouse.B.finalPrice+ram.B.finalPrice+monitor.B.finalPrice;
		
		System.out.println("--------------------------------------------------------------------------------------------------------------------------");
		System.out.println("--------------------------------------------------------------------------------------------------------------------------");
		System.out.println("----------------------------------------------------------Bill no:-"+mb.B.billNo+"------------------------------------------------------");
		System.out.println("	Product		BaseProductPrice	ServiceTax	TransportTax	StateTax	CentralTax	FinalPrice");
		System.out.println("--------------------------------------------------------------------------------------------------------------------------");
		System.out.println("	MotherBoard \t"+mb.B.baseProductPrice+"\t\t\t"+mb.B.serviceTax+"\t\t"+mb.B.TransportTax+"\t\t"+mb.B.stateTax+"\t\t"+mb.B.centralTax+"\t\t"+mb.B.finalPrice);
		System.out.println("	KeyBoard	"+kb.B.baseProductPrice+"\t\t\t"+kb.B.serviceTax+"\t\t"+kb.B.TransportTax+"\t\t"+kb.B.stateTax+"\t\t"+kb.B.centralTax+"\t\t"+kb.B.finalPrice);
		System.out.println("	CPU		"+cpu.B.baseProductPrice+"\t\t\t"+cpu.B.serviceTax+"\t\t"+cpu.B.TransportTax+"\t\t"+cpu.B.stateTax+"\t\t"+cpu.B.centralTax+"\t\t"+cpu.B.finalPrice);
		System.out.println("	Mouse		"+mouse.B.baseProductPrice+"\t\t\t"+mouse.B.serviceTax+"\t\t"+mouse.B.TransportTax+"\t\t"+mouse.B.stateTax+"\t\t"+mouse.B.centralTax+"\t\t"+mouse.B.finalPrice);
		System.out.println("	Ram		"+ram.B.baseProductPrice+"\t\t\t"+ram.B.serviceTax+"\t\t"+ram.B.TransportTax+"\t\t"+ram.B.stateTax+"\t\t"+ram.B.centralTax+"\t\t"+ram.B.finalPrice);
		System.out.println("	Monitor		"+monitor.B.baseProductPrice+"\t\t\t"+monitor.B.serviceTax+"\t\t"+monitor.B.TransportTax+"\t\t"+monitor.B.stateTax+"\t\t"+monitor.B.centralTax+"\t\t"+monitor.B.finalPrice);
		System.out.println("---------------------------------------------------------------------------------------------------------------------------");
		System.out.println("	Total		"+bpp	+"\t\t\t"+st	+"\t\t"+tt		+"\t\t"+stt	+"\t\t"+ct	+"\t\t"+fp);
		System.out.println("---------------------------------------------------------------------------------------------------------------------------");
		System.out.println("----------------------------------------------------------Bill no:-"+mb.B.billNo+"-------------------------------------------------------");
		System.out.println();
		System.out.println();
		System.out.println();
		
		
	}
}
